/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.epn.poo.Interfaces;

import com.epn.poo.ClasesAdministracionColegio.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebas Molina
 */
public class CrearCurso extends javax.swing.JDialog {

    DefaultComboBoxModel<String> nombresMateria;
    DefaultTableModel modeloTabla;
    ArrayList<Profesor> listaProfesores;
    ArrayList<Estudiante> listaEstudiante;
    Curso cursoG = new Curso();

    /**
     * Creates new form CrearCurso
     *
     * @param parent
     * @param listaEstudiantes
     * @param listaProfesor
     * @param modal
     */
    public CrearCurso(java.awt.Frame parent, ArrayList<Estudiante> listaEstudiantes, ArrayList<Profesor> listaProfesor, boolean modal) {
        super(parent, modal);
        initComponents();
        this.listaProfesores = listaProfesor;
        this.listaEstudiante = listaEstudiantes;
        settearMateriasEnCB();
        cargarDatosEstudianteEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombreCurso = new javax.swing.JTextField();
        jCBMaterias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jBAgregarMateria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaEstudiantes = new javax.swing.JTable();
        jBAgregarEstudiante = new javax.swing.JButton();
        jBCrearCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CREAR CURSO");

        jLabel2.setText("Nombre:");

        jCBMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMateriasActionPerformed(evt);
            }
        });

        jLabel3.setText("Materia:");

        jBAgregarMateria.setText("AGREGAR MATERIA");
        jBAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarMateriaActionPerformed(evt);
            }
        });

        jTablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Estudiantes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaEstudiantes);

        jBAgregarEstudiante.setText("AGREGAR ESTUDIANTE");
        jBAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarEstudianteActionPerformed(evt);
            }
        });

        jBCrearCurso.setText("CREAR CURSO");
        jBCrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jBCrearCurso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAgregarEstudiante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)
                                .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAgregarMateria))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAgregarEstudiante)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jBAgregarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jBCrearCurso)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearCursoActionPerformed
        // TODO add your handling code here:
        if (cursoG.getListaProfesores().size() != 3) {
            JOptionPane.showMessageDialog(null, "El curso debe tener tres materias/profesores para ser creado");
            return;
        }
        if (cursoG.getListaEstudiantes().size() < 10) {
            JOptionPane.showMessageDialog(null, "El curso debe tener diez estudiantes para ser creado");
            return;
        }
        cursoG.setNombreCurso(jTNombreCurso.getText());
        JOptionPane.showMessageDialog(null, "Curso creado con exito");
        this.dispose();
    }//GEN-LAST:event_jBCrearCursoActionPerformed

    private void jCBMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBMateriasActionPerformed

    private void jBAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarEstudianteActionPerformed
        // TODO add your handling code here:
        if (cursoG.getListaEstudiantes().size() == 10) {
            JOptionPane.showMessageDialog(null, "Se alcanzo el limite de estudiantes por curso");
            return;
        }
        cursoG.agregarEstudianteEnCurso(getEstudianteSeleccionado(listaEstudiante));
        // eliminar del jtable al estudiante seleccionado, para no seleccionarlo dos veces
        modeloTabla.removeRow(jTablaEstudiantes.getSelectedRow());
        jTablaEstudiantes.clearSelection();
    }//GEN-LAST:event_jBAgregarEstudianteActionPerformed

    private void jBAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarMateriaActionPerformed
        // TODO add your handling code here:
        if (cursoG.getListaProfesores().size() == 3) {
            JOptionPane.showMessageDialog(null, "Se alcanzo el limite de materias/profesores por curso");
            return;
        }
        cursoG.agregarProfesorEnCurso(getProfesorSeleccionado(listaProfesores));
    }//GEN-LAST:event_jBAgregarMateriaActionPerformed

    public Curso getCursoCreado() {
        return cursoG;
    }

    public Profesor getProfesorSeleccionado(ArrayList<Profesor> listaProf) {
        String profSeleccionado = getIdSeleccionado();
        for (Profesor p : listaProf) {
            if (p.getUsuarioProf().equals(profSeleccionado)) {
                return p;
            }
        }
        return null;
    }

    public String getNombreEstudianteSeleccionado() {
        String nombreEstudiante = "";
        int filaSeleccionada = jTablaEstudiantes.getSelectedRow();
        if (filaSeleccionada != -1) {
            nombreEstudiante = jTablaEstudiantes.getValueAt(filaSeleccionada, 0).toString();
        }
        return nombreEstudiante;
    }

    public Estudiante getEstudianteSeleccionado(ArrayList<Estudiante> listaEst) {
        String nombreSeleccionado = getNombreEstudianteSeleccionado();
        for (Estudiante e : listaEst) {
            if (e.getNombreP().equals(nombreSeleccionado)) {
                return e;
            }
        }
        return null;
    }

    public void settearMateriasEnCB() {
        nombresMateria = new DefaultComboBoxModel<>();
        nombresMateria.addElement("Seleccione una opcion...");
        ArrayList<String> materiaYProfesor = new ArrayList<>();
        for (Profesor p : listaProfesores) {
            materiaYProfesor.add(p.getUsuarioProf() + "-" + p.getNombreP() + "-" + p.getEspecialidadProf());
        }

        for (String s : materiaYProfesor) {
            nombresMateria.addElement(s);
        }
        jCBMaterias.setModel(nombresMateria);
    }

    public void cargarDatosEstudianteEnTabla() {
        modeloTabla = (DefaultTableModel) jTablaEstudiantes.getModel();
        modeloTabla.setRowCount(0);
        for (Estudiante est : listaEstudiante) {
            Object[] fila = {est.getNombreP()};
            modeloTabla.addRow(fila);
        }
        jTablaEstudiantes.setModel(modeloTabla);
    }

    public String getIdSeleccionado() {
        String jcbSeleccion = (String) jCBMaterias.getSelectedItem();
        String[] partes = jcbSeleccion.split("-");
        return partes[0];
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearCurso dialog = new CrearCurso(new javax.swing.JFrame(), new ArrayList<>(), new ArrayList<>(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarEstudiante;
    private javax.swing.JButton jBAgregarMateria;
    private javax.swing.JButton jBCrearCurso;
    private javax.swing.JComboBox<String> jCBMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNombreCurso;
    private javax.swing.JTable jTablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
