/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.epn.poo.Interfaces;

import com.epn.poo.ClasesAdministracionColegio.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class LoginPrincipal extends javax.swing.JFrame {

    String idAdmin = "ADM100";
    String passwordAdmin = "admin1234";

    /**
     * Creates new form LoginPrincipal
     */
    public LoginPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jTContrasena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBLogin.setText("LOGIN");
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE ADMINISTRACION DE COLEGIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setOpaque(true);

        jLabel2.setText("Usuario: ");

        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        try {
            // TODO add your handling code here:
            String usuarioVerificar = jTUsuario.getText().substring(0, 3).toUpperCase();
            String userCompleto = jTUsuario.getText().trim().toUpperCase();
            String contrasena = jTContrasena.getText();
            if (!comprobarContrasena(userCompleto, contrasena)) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
                return;
            }
            switch (usuarioVerificar) {
                case "ADM":
                    AdministradorInterfaz ventanaAdmin = new AdministradorInterfaz(this, true);
                    ventanaAdmin.setLocationRelativeTo(null);
                    ventanaAdmin.setVisible(true);
                    break;
                case "EST":
                    EstudianteInterfaz ventanaEstudiante = new EstudianteInterfaz(this, userCompleto, true);
                    ventanaEstudiante.setLocationRelativeTo(null);
                    ventanaEstudiante.setVisible(true);
                    break;
                case "PRF":
                    ProfesorInterfaz ventanaProfesor = new ProfesorInterfaz(this, userCompleto, true);
                    ventanaProfesor.setLocationRelativeTo(null);
                    ventanaProfesor.setVisible(true);
                    break;
                default:
                    throw new AssertionError();
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBLoginActionPerformed

    public boolean comprobarContrasena(String usuario, String contrasena) {
        ArrayList<Estudiante> listaEstudiantes = cargarEstudiantesDesdeArchivo("archivos/registrosEstudiante");
        ArrayList<Profesor> listaProfes = cargarProfesoresDesdeArchivo("archivos/registrosProfesor");
        String usuarioVerificar = jTUsuario.getText().substring(0, 3).toUpperCase();
        if (usuarioVerificar.equals("EST")) {
            for (Estudiante e : listaEstudiantes) {
                if (e.getUsuarioEst().equals(usuario) && e.getContrasenaEst().equals(contrasena)) {
                    return true;
                }
            }
        } else if (usuarioVerificar.equals("PRF")) {
            for (Profesor p : listaProfes) {
                if (p.getUsuarioProf().equals(usuario) && p.getContrasenaProf().equals(contrasena)) {
                    return true;
                }
            }
        } else if (usuarioVerificar.equals("ADM")) {
            if (usuario.equals(idAdmin) && contrasena.equals(passwordAdmin)) {
                return true;
            }
        }
        return false;
    }

    public ArrayList<Estudiante> cargarEstudiantesDesdeArchivo(String ruta) {
        ArrayList<Estudiante> lista = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(ruta))) { //Abre el archivo seleccionado
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(";"); //Pone en un arreglo los diferentes datos del archivo, para verificarlos o settearlos
                if (partes.length == 6) {
                    Estudiante est = new Estudiante();
                    est.setUsuarioEst(partes[0]);
                    est.setContrasenaEst(partes[1]);
                    est.setNombreP(partes[2]);
                    est.setCedulaP(partes[3]);
                    est.setEdadP(Integer.parseInt(partes[4]));
                    est.setTelefonoP(partes[5]);
                    lista.add(est); //Agrega el objeto creado en una lista, para retornarla
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar estudiante: " + e.getMessage());
        }
        return lista;
    }

    public ArrayList<Profesor> cargarProfesoresDesdeArchivo(String ruta) {
        ArrayList<Profesor> lista = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(";");
                if (partes.length == 7) {
                    Profesor prof = new Profesor();
                    prof.setUsuarioProf(partes[0]);
                    prof.setContrasenaProf(partes[1]);
                    prof.setNombreP(partes[2]);
                    prof.setEdadP(Integer.parseInt(partes[3]));
                    prof.setCedulaP(partes[4]);
                    prof.setTelefonoP(partes[5]);
                    prof.setEspecialidadProf(partes[6]);
                    lista.add(prof);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar profesor: " + e.getMessage());
        }
        return lista;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTContrasena;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
