/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.epn.poo.Interfaces;

import com.epn.poo.ClasesAdministracionColegio.Estudiante;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class MatricularEstudiante extends javax.swing.JDialog {

    Estudiante estudianteG = new Estudiante();

    /**
     * Creates new form MatricularEstudiante
     * @param parent
     * @param modal
     */
    public MatricularEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTNombreEst = new javax.swing.JTextField();
        jTEdadEst = new javax.swing.JTextField();
        jTCedulaEst = new javax.swing.JTextField();
        jTTelefonoEst = new javax.swing.JTextField();
        jBMatricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("MATRICULACION");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        jLabel4.setText("Cedula:");

        jLabel5.setText("Telefono:");

        jBMatricular.setText("MATRICULAR");
        jBMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNombreEst, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTEdadEst)
                            .addComponent(jTCedulaEst)
                            .addComponent(jTTelefonoEst))))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jBMatricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTEdadEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTCedulaEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTTelefonoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBMatricular)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMatricularActionPerformed
        // TODO add your handling code here:
        if (jTNombreEst.getText().isEmpty() || jTEdadEst.getText().isEmpty() || jTCedulaEst.getText().isEmpty() || jTTelefonoEst.getText().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos"); //Verificar que los campos no esten vacios
            return;
        }
        //Setteo de los datos en un objeto Estudiante
        estudianteG.setNombreP(jTNombreEst.getText());
        if (!validarEdad(jTEdadEst.getText())) {
            JOptionPane.showMessageDialog(null, "Edad invalida");
            jTEdadEst.setText("");
            return;
        }
        estudianteG.setEdadP(Integer.parseInt(jTEdadEst.getText()));
        if (!validarCedulaEcuatoriana(jTCedulaEst.getText())) {
            JOptionPane.showMessageDialog(null, "Cedula invalida");
            jTCedulaEst.setText("");
            return;
        }
        estudianteG.setCedulaP(jTCedulaEst.getText());
        if (!validarTelefono(jTTelefonoEst.getText())) {
            JOptionPane.showMessageDialog(null, "Telefono invalido");
            jTTelefonoEst.setText("");
            return;
        }
        estudianteG.setTelefonoP(jTTelefonoEst.getText());
        JOptionPane.showMessageDialog(null, "Estudiante matriculado\n Usuario: " + estudianteG.getUsuarioEst() + "\nContraseña: " + estudianteG.getContrasenaEst()); //Mostrar Usuario y Contrasena
        this.dispose();
    }//GEN-LAST:event_jBMatricularActionPerformed

    // Metodo para retornar el estudiante creado
    public Estudiante getEstudianteCreado() {
        return estudianteG;
    }
    
    public boolean validarCedulaEcuatoriana(String cedula) {
        int provincia = Integer.parseInt(cedula.substring(0, 2));
        int tercerDigito = Integer.parseInt(cedula.substring(2, 3));
        if (cedula == null || cedula.length() != 10 || !cedula.matches("\\d+")) {
            return false;
        }
        if (provincia < 1 || provincia > 24 || tercerDigito >= 6) {
            return false;
        }

        int[] coeficientes = {2, 1, 2, 1, 2, 1, 2, 1, 2};
        int suma = 0;

        for (int i = 0; i < 9; i++) {
            int digito = Character.getNumericValue(cedula.charAt(i));
            int producto = digito * coeficientes[i];
            if (producto >= 10) {
                producto -= 9;
            }
            suma += producto;
        }

        int digitoVerificador = (10 - (suma % 10)) % 10;

        int ultimoDigito = Character.getNumericValue(cedula.charAt(9));
        return digitoVerificador == ultimoDigito;
    }

    public boolean validarTelefono(String telefono) {
        if (telefono.length() != 10) {
            return false;
        }
        return true;
    }

    public boolean validarEdad(String edadTexto) {
        try {
            int edad = Integer.parseInt(edadTexto); // Intenta convertir a número
            return edad > 0; // Retorna true solo si es mayor que cero
        } catch (NumberFormatException e) {
            return false; // Si no es un número, retorna false
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatricularEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MatricularEstudiante dialog = new MatricularEstudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMatricular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTCedulaEst;
    private javax.swing.JTextField jTEdadEst;
    private javax.swing.JTextField jTNombreEst;
    private javax.swing.JTextField jTTelefonoEst;
    // End of variables declaration//GEN-END:variables
}
